### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by baimour** [rponeawa/thermalmonitordDisabler#3]
能不能把SparseBox的绕过自签限制功能加入到这里？

**Comment by rponeawa** [comment]
目前来说只考虑添加修改 disabled.plist 的相关功能

**Comment by banjianti** [comment]
为啥不提供exe程序下载，python老出错，环境匹配不上

**Comment by rponeawa** [comment]
> 为啥不提供exe程序下载，python老出错，环境匹配不上

因为国内平台（例如闲鱼）上对本程序的倒卖。
运行方式已在 readme 中写出。
