### ISSUE TITLE
大佬，18.2 Beta3 遇到”应用更改时发生错误:“

### ISSUE THREAD

**Issue by Ray-Bugkiller** [rponeawa/thermalmonitordDisabler#4]
1. 查找手机已禁用
2. 信任电脑已经可以正常识别
3. 温控、更新、日志选项均遇到这个情况
版本是18.2(22C5142a)

**Comment by Ray-Bugkiller** [comment]
我是通过18.2beta2的旧手机禁用后，导数据到新手机的18.2beta3，在新手机上遇到的这个问题

**Comment by Ray-Bugkiller** [comment]
如果我现在只是想解开对软件更新的禁用，重新刷一遍beta3有用吗？

**Comment by rponeawa** [comment]
该版本不受支持 最高支持到 iOS 18.2 Beta 2

**Comment by rponeawa** [comment]
> 如果我现在只是想解开对软件更新的禁用，重新刷一遍beta3有用吗？

你可以在旧手机上解除禁用后，将新手机恢复出厂再重新迁移数据到新手机。或是将新手机降级至 iOS 18.1 Beta 2 及以下再使用工具。

**Comment by Ray-Bugkiller** [comment]
> > 如果我现在只是想解开对软件更新的禁用，重新刷一遍beta3有用吗？
> 
> 你可以在旧手机上解除禁用后，将新手机恢复出厂再重新迁移数据到新手机。或是将新手机降级至 iOS 18.1 Beta 2 及以下再使用工具。

谢谢大佬~ beta3到2可以保留数据降级吗？如果您知道的话。

**Comment by rponeawa** [comment]
> > > 如果我现在只是想解开对软件更新的禁用，重新刷一遍beta3有用吗？
> > 
> > 你可以在旧手机上解除禁用后，将新手机恢复出厂再重新迁移数据到新手机。或是将新手机降级至 iOS 18.1 Beta 2 及以下再使用工具。
> 
> 谢谢大佬~ beta3到2可以保留数据降级吗？如果您知道的话。

据我所知是不行的。可以通过修改 iTunes 备份文件的方式在旧版本复原来自新版的完全备份，但可能会引起未知的 bug。

**Comment by Ray-Bugkiller** [comment]
> > > > 如果我现在只是想解开对软件更新的禁用，重新刷一遍beta3有用吗？
> > > 
> > > 
> > > 你可以在旧手机上解除禁用后，将新手机恢复出厂再重新迁移数据到新手机。或是将新手机降级至 iOS 18.1 Beta 2 及以下再使用工具。
> > 
> > 
> > 谢谢大佬~ beta3到2可以保留数据降级吗？如果您知道的话。
> 
> 据我所知是不行的。可以通过修改 iTunes 备份文件的方式在旧版本复原来自新版的完全备份，但可能会引起未知的 bug。

Hi 大佬，我晚上尝试了一下，用B2版本包内的044-47650-036.dmg.aea替换B3版本里面的文件，爱思保数据刷成功了，通话记录和短信被清空了，其他的数据都正常。
我用3.2版本的工具成功恢复了温控和更新的状态，感谢你的工具~
