### ISSUE TITLE
Mdm Profile disapears

### ISSUE THREAD

**Issue by MegaFTW3** [rponeawa/thermalmonitordDisabler#7]
Please add a feature similar to Nugget to disable Skip Setup

**Comment by luhgarlicbread** [comment]
> Please add a feature similar to Nugget to disable Skip Setup

I essentially requested this awhile ago too. rponeawa said it was a feature to be on the way! 🤷‍♂️

**Comment by rponeawa** [comment]
https://github.com/rponeawa/thermalmonitordDisabler/releases/tag/v3.4
